### PR TITLE
Minor refactor

### PR DESCRIPTION
**Pull request by delirious-lettuce**
I just saw your post on reddit and thought I would take a look.

Summary of changes:
* Use `snake_case` for function names (PEP8)
* Use 4 space indentation (instead of tabs)
* Moved excess code from `try` to `else`
    > The use of the else clause is better than adding additional code to the try clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the try … except statement.
* Use `str.format` wherever possible (readability)
* Got rid of `try/except` in `change_dir` since using `os.makedirs` with `exist_ok=True` handles if the directory exists previously or not
* Removed `sys_arg_check` and used `argparse.ArgumentParser` instead
* Running `main.py` from the command-line with no arguments simply downloads the latest comic.
* You can use `-h` or `--help` for `ArgumentParser`s built-in help.
* If the `-r` or `--random` arg is set, then a random comic is downloaded. 
* If the `-n` or `--number` arg is set, then an integer must be given and that particular comic will be downloaded.
* Because of `mutually_exclusive_group`, only one of either `--random` or `--number` may be set at a time.

Although you seemed to be importing BeautifulSoup (`bs4`) originally, it wasn't being used so I removed that import. I didn't take the extra time to replace the html parsing code you wrote but that would be a great next step since using BeautifulSoup is much better than doing it yourself.

Anyways, good luck with your project!

### CODE REVIEW

**Comment by hunterkepley** [comment]
Wonderful, this helps a lot with my learning process with this! I'll merge it right away good sir.

**Comment by delirious-lettuce** [comment]
@hunterkepley ,

Glad to help! Sometimes just seeing a new/different way of writing things can be very helpful (I know it was for me when I was first learning Python).

**Comment by hunterkepley** [comment]
Yeah! I used python as my first language but for nothing proper, so I'm trying to get good at it as well as Go right now

**Comment by delirious-lettuce** [comment]
Nice! I actually just bought my first book on Go a couple days ago.

Well, good luck with Python & Go!

**Comment by hunterkepley** [comment]
You too with Go!

**Pull request merged**
